### PR TITLE
Enhance structure and add listing option

### PR DESCRIPTION
**Pull request by cmkramer**
This pull request fixes some double future resolve problems introduced in the previous and adds 2 new functions:

* The ability to optionally bind after a check, to allow checking for existence without having to supply a password (required to validate if a supplied LDAP account exists when associating an application entity to an LDAP account)
* The ability to retrieve a listing of ldap accounts in the supplied dn, which makes it possible to search the directory (required for client-sided autocomplete/typeahead)

### CODE REVIEW

**Comment by ilfrich** [comment]
Are you sure this change is correct? It seems like this PR converts this login/account package into an LDAP search package?! The primary objective of this package should be the ability to log-in using LDAP and not to search for users... 

I was trying to migrate the package to Meteor 1.3, because out-of-the-box it wouldn't work anymore with the `searchBeforeBind` functionality, where it was possible to use the username and search a field in LDAP for the username, to retrieve the DN **in order to authenticate**.

Additionally the "new" functionality is not documented at all...

**Comment by cmkramer** [comment]
@ilfrich thank you for the feedback. The changes should make it possible to:

* authenticate before a "searchBeforeBind" which would be required in a registry that does not allow anonymous searches
* check for existence without binding
* list without binding

The latter two dont require you to supply a password as they basically execute a searchBeforeBind action without the consequential binding. Considering the scope of the library to me it made sense to add this enhancement as it provides a lot more flexibility at very low additional cost of complexity.

Now I changed it in order to fill a gap on my end and made a pull request to share. It could be that I missed something during the testing of the adjustments since the lib does not incluse a regression set. If so, please do share the problem and if possible a fix. 

It would be valuable to adjust the docs with the added features and include some form of regression testing. If my proposed changes caused you any trouble I appologize. The setup works in my application with the whole feature set used, except for anonymous searching.

Kind regards,

Chris

**Comment by ilfrich** [comment]
@cmkramer Anonymous search is precisely what I need. Imagine your users use their email address to authenticate, but the `dn` is a different string, which even the user doesn't know (just a technical unique identifier). In this scenario, you need to search using the email to retrieve the LDAP record and then extract the `dn` from that record in order to bind.

Additionally I don't think this package should provide the following 2 features:

* check for existence without binding
* list without binding

Searching an LDAP / AD is a different task, which should be handled in a different package in order to keep it focused. Other accounts packages follow the same guidelines (e.g. `accounts-facebook`).

**Comment by cmkramer** [comment]
@ilfrich oh don't get me wrong. By saying "except anonymous search" I mean I don't use it in the application I use the library for. It doesn't mean that I believe it should not be included as a functionality. So if that would be broken it needs fixing.

The other part I can't say. It's not up to me to decide the vision and scoping behind this package. Could be that you're right, I just prefer to avoid having to basically write the same code again for another dependency, which returns a slightly different result.

Concerning the testing, you'd probably need a mock for the ldap server to at least unit test the setup. It could include an integration test with a standard open ldap testing server, yet that would probably not cover the whole nine yards.

**Comment by cmkramer** [comment]
Oh and concerning your described scenario on the anonymous search. The ldap I'm using only allows what you describe through an authenticated user. So basically the application has its own credentials for ldap, which allow it to query in order to avoid anyone or any application connected to the network to be able to query ldap. 

Result is that you "bindBeforeFind" with the application credentials and "bindAfterFind" with the user supplied credentials in case of a proper login.

**Pull request merged**
